### ISSUE TITLE
LinkingError is missing from the Spanish messages.yml

### ISSUE THREAD

**Issue by Zixasis** [DiscordSRV/DiscordSRV#1121]
**when the server starts it throws me this error (which previously did not happen)**

```
[01:58:15 INFO]: [DiscordSRV] Enabling DiscordSRV v1.22.0
[01:58:15 WARN]: [DiscordSRV] Config key LinkingError is missing from the messages.yml. Using the default value of &cCurrently unable to link accounts due to an internal error. Contact your server administration team.

```
```yml

DiscordToMinecraftChatMessageFormat: "[<aqua>Discord</aqua> | %toprolecolor%%toprolealias%<reset>] %name% » %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[<aqua>Discord</aqua>] %name% » %message%"
DiscordToMinecraftAllRolesSeparator: " | "

MinecraftChatToDiscordMessageFormat: "*%displayname% » %message%"
MinecraftChatToDiscordMessageFormatNoPrimaryGroup: "%displayname% » %message%"

ChatChannelHookMessageFormat: "%channelcolor%[%channelnickname%]&r %message%"

DynmapNameFormat: "[Discord | %toprolealias%] %username%"
DynmapChatFormat: "%message%"
DynmapDiscordFormat: "[Dynmap] %name% » %message%"

DiscordConsoleChannelFormat: "[%datetime% %level%] %line%"
DiscordConsoleChannelMessagePrefix: ""
DiscordConsoleChannelMessageSuffix: ""


DiscordChatChannelConsoleCommandNotifyErrorsFormat: "**%user%**, trataste de ejecutar un comando. Lamentablemente, hubo un error: %error%"

DiscordChatChannelListCommandFormatOnlinePlayers: "**Jugadores Online (%playercount%):**"
DiscordChatChannelListCommandFormatNoOnlinePlayers: "**Sin jugadores Online**"
DiscordChatChannelListCommandPlayerFormat: "%displayname%"
DiscordChatChannelListCommandAllPlayersSeparator: ", "

MinecraftPlayerJoinMessage:
  Enabled: true
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#00ff00"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: "%username% Entró al servidor"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false

MinecraftPlayerFirstJoinMessage:
  Enabled: true
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#ffd700"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: "%username% Entró al servidor por primera vez"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false

MinecraftPlayerLeaveMessage:
  Enabled: true
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#ff0000"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: "%username% Salió del servidor"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false

MinecraftPlayerDeathMessage:
  Enabled: true
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#000000"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: "%deathmessage%"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false

MinecraftPlayerAchievementMessage:
  Enabled: true
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#ffd700"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: "%displayname% ha conseguido el progreso %achievement%!"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false

ChannelTopicUpdaterChatChannelTopicFormat: "%playercount%/%playermax% jugadores online | Se han unido %totalplayers% jugadores únicos | Servidor online por %uptimemins% minutos | Última actualizacion: %date%"
ChannelTopicUpdaterConsoleChannelTopicFormat: "TPS: %tps% | Mem: %usedmemorygb%GB usada/%freememorygb%GB libre/%maxmemorygb%GB max | %serverversion%"
ChannelTopicUpdaterChatChannelTopicAtServerShutdownFormat: "El servidor está Offline | Se han unido %totalplayers% jugadores únicos"
ChannelTopicUpdaterConsoleChannelTopicAtServerShutdownFormat: "El servidor está Offline | %serverversion%"

DiscordCommandFormat: "&bÚnete a nuestro servidor de Discord {INVITE}. Para ayuda con los comandos, ejecute \"/discord ?\""

NoPermissionMessage: "&cFalta el formato del mensaje de permiso"

UnknownCommandMessage: "&bEste comando no existe"

DiscordChatChannelServerStartupMessage: ":white_check_mark: **Servidor iniciado**"
DiscordChatChannelServerShutdownMessage: ":octagonal_sign: **Servidor detenido**"


ServerWatchdogMessage: "`%date%` %guildowner%, la sala de servidores está encendida :fire::bangbang:"

CodeGenerated: "Su código de vinculación es %code%. Envíele un MP al bot (%botname%) en Discord, incluyendo solamente el código de vinculación."
UnknownCode: "No conozco ese código, inténtelo de nuevo."
InvalidCode: "¿Estás seguro de que ese es tu código? Los códigos de enlace tienen 4 números de largo"
DiscordAccountLinked: "Su cuenta de Discord ha sido vinculada a %name% (%uuid%)"
DiscordAccountAlreadyLinked: "Ya estás vinculado a %username% (%uuid%)"
DiscordLinkedAccountRequired: "Intentaste decir el siguiente mensaje en el chat del juego, pero este servidor requiere que tenga su cuenta de Minecraft vinculada a su cuenta de Discord. Vincúlelo en el juego ejecutando `/discord link`. \n```%message%```"
DiscordLinkedAccountCheckFailed: "No se puede verificar si su cuenta está vinculada, vuelva a intentarlo más tarde"

ClickToCopyCode: "Haga clic para copiar"
MinecraftAccountLinked: "&bSu UUID ha sido vinculado al usuario de Discord %username% (%id%)"
MinecraftAccountAlreadyLinked: "&bSu cuenta de Minecraft ya está asociada a una cuenta Discord. Si tiene permiso, puede desvincular su cuenta con /discord unlink."
LinkedCommandSuccess: "&bTu cuenta de Minecraft está asociada con %name%"
UnlinkCommandSuccess: "&bTu cuenta de Minecraft ya no está asociada con %name%"
MinecraftNoLinkedAccount: "&cTu cuenta de Minecraft no está asociada con una cuenta de Discord"
MinecraftNobodyFound: "&cNo se encontrá a nadie con Discord ID/nombre de Discord/nombre de Minecraft/Minecraft UUID que coincida con \"%target%\" para buscar"

```

**Comment by Vankka** [comment]
That is showing because, as it states your messages file does not have that option. It's normally just above `LinkingError`, like this:
```yaml
MinecraftNoLinkedAccount: "&cYour Minecraft account isn't associated with a Discord account."
LinkingError: "&cCurrently unable to link accounts due to an internal error. Contact your server administration team."
MinecraftNobodyFound: "&cNobody found with Discord ID/Discord name/Minecraft name/Minecraft UUID matching \"%target%\" to look up."
```
