### ISSUE TITLE
Ability to set some syncs as Discord-authoritative and some as MC-authoritative

### ISSUE THREAD

**Issue by srnyx** [DiscordSRV/DiscordSRV#1249]
### Why?

**Discord:** Owner, Admin, Mod, Builder, Tier 3, Tier 2, Tier 1, Epic, Famous
**Minecraft:** Owner, Admin, Mod, Builder, Diamond, Gold, Iron, Famous

**Syncs:**
Owner - Owner
Admin - Admin
Mod - Mod
Builder - Builder
Tier 3 - Diamond
Tier 2 - Gold
Tier 1 - Iron
Epic - Iron *(uses `discordsrv.sync.rank`)*
Famous - Famous
*Iron group (which Gold and Diamond inherit from) has `discordsrv.sync.rank` which syncs to Epic role.*

I would want all the staff syncs (Owner, Admin, Mod, and Builder), tier syncs (Tier 3, Tier 2, Tier 1), and Famous sync to sync Discord to Minecraft.
I would want all the Epic syncs to sync Minecraft to Discord.

I've tried so many things to get it to work, but it just won't. I've asked for support in the Discord but they also said that there isn't a good setup for what I wanted.

### What and How?

I think something in `synchronization.yml` like this would work great:
```yml
# GroupRoleSynchronizationMinecraftAuthoratativeGroups: groups listed here will be authoritative over their Discord counterparts. Groups here must be in GroupRoleSynchronizationGroupsAndRolesToSync.
# GroupRoleSynchronizationDiscordAuthoratativeRoles: the same as GroupRoleSynchronizationMinecraftAuthoratativeGroups except for Discord roles. Use IDs, not names. Role IDs here must also be in GroupRoleSynchronizationGroupsAndRolesToSync
GroupRoleSynchronizationMinecraftAuthoratativeGroups: ["group1", "group2", "group3"]
GroupRoleSynchronizationDiscordAuthoratativeRoles: ["roleid1", "roleid2", "roleid3"]
```

### Are there alternatives?

Not that I, or @Dinty1, could think of. But, I'll gladly try any ideas that someone comes up with.
*No, `GroupRoleSynchronizationMinecraftIsAuthoritative` will not work as it makes **all** authoratative.*

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.
