### ISSUE TITLE
Add support for "Components" for Discord messages.

### ISSUE THREAD

**Issue by Wolfie713** [DiscordSRV/DiscordSRV#1385]
### Why?

One feature it has that I believe people would find quite useful, at least for custom alerts, is being able to make use of Discords "Components" feature.  One specific part of it in particular, which is being able to make buttons that have a label that (when clicked) lead to URL's.  Of course, it allows the use of buttons for other reasons, or drop down menu items.  Either way, might be worth adding and seeing what people come up with when using it.

![image](https://user-images.githubusercontent.com/8166710/160945806-7e59bb0f-6ab0-44b7-bdb9-15da2d762fa2.png)
_The "Primary/Secondary/Success/Danger/Link" text in the buttons are what type of buttons they are.  Different text can be used, I only used the names to make it simple._

### What and How?

It should allow the components feature of Discord messages to be used.

Example of what I'm thinking it would look like in the alerts.yml file.  Obviously how it would really work would be up to how it's implemented, this is only to give an idea of what I'm thinking.
```
    Component:
      -
        - Style: 1
          Label: "Primary"
          Type: 2
        - Style: 2
          Label: "Secondary"
          Type: 2
        - Style: 3
          Label: "Success"
          Type: 2
        - Style: 4
          Label: "Danger"
          Type: 2
        - Style: 5
          Label: "Link"
          Url: "http://link.to/some/url"
          Type: 2
        - Type: 3
          Options:
            - Label: "Drop Down"
              Value: "dd"
              Description: "Description"
              Default: "true"
            - Label: "menu list"
              Value: "ml"
              Description: "I'm a gummy bear."

```

### Are there alternatives?

Not that I know of.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.
