### ISSUE TITLE
Assign Multiple Roles

### ISSUE THREAD

**Issue by Toodixx** [DiscordSRV/DiscordSRV#1390]
### Why?

Allow multiple discord roles to be assigned if a user gets a role in Minecraft (e.g if they have admin in-game assign admin as well as staff on discord. I feel this would allow discord servers to have more control over the perms for each rank and make the system more user friendly

### What and How?

Allow multiple roles to be assigned on discord for each Minecraft role in the config
{"Mod": "00STAFF00", "00MOD00"} or {"Admin": "00STAFF00" "00ADMIN00"}

### Are there alternatives?

Set the bot the auto-update roles if a user has XX on discord and assign YY as well 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
This can already be done by assigning the Staff role to a "fake" group called Staff and then assigning the `discordsrv.sync.Staff` permission to whatever groups should also inherit this role. Example:
```yaml
# Group sync config
GroupRoleSynchronizationGroupsAndRolesToSync: {"Mod": "modroleid", "Admin": "adminroleid", "Staff": "staffroleid"}

# And then give these permissions
Mod: discordsrv.sync.Staff
Admin: discordsrv.sync.Staff
```
