### ISSUE TITLE
Option to use global context for group sync

### ISSUE THREAD

**Issue by twiceineverymoment** [DiscordSRV/DiscordSRV#1414]
### Why?

When enabling discord->minecraft group/role sync, the Minecraft groups are granted in LuckPerms with the context server=(the name of the server running DiscordSRV.) This makes it impossible for a Velocity proxy to pick up the permission changes as its context is always different.

### What and How?

Add an option in synchronization.yml to apply the LuckPerms changes with the context "global" rather than a server-specific one, so the grants can apply to other servers and to the proxy.

### Are there alternatives?

Unsure, apart from adding full Velocity support which seems unlikely.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
Group synchronization with LuckPerms setting the `server=<server name>` context is controlled by the `vault-server` option (or `server` if `use-vault-server` is disabled) in LuckPerms' config.yml
```yaml
# If the vault-server option below should be used.
#
# - When this option is set to false, the server value defined above under "server" is used.
use-vault-server: false

# The name of the server used within Vault operations.
#
# - If you don't want Vault operations to be server specific, set this to "global".
# - Will only take effect if use-vault-server is set to true above.
vault-server: global
```
