### ISSUE TITLE
Add %toprolecolor% placeholder for %name%s in %reply% 

### ISSUE THREAD

**Issue by Epikest** [DiscordSRV/DiscordSRV#1419]
### Why?

i think it would be neat to have the top role color show for names in `DiscordToMinecraftMessageReplyFormat`
this will make the chat a bit more colorful

### What and How?

example:
```yml
DiscordToMinecraftChatMessageFormat: "<%toprolecolor%%name%%reply%&r> %message%"
DiscordToMinecraftChatMessageFormatNoRole: "<%name%%reply%&r> %message%"
DiscordToMinecraftMessageReplyFormat: " → %toprolecolor%%name%" # currently, you can't use %toprolecolor% here
```

### Are there alternatives?

no

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.
