### ISSUE TITLE
Run console command on alert trigger

### ISSUE THREAD

**Issue by BoredManCodes** [DiscordSRV/DiscordSRV#1426]
### Why?

To allow more control over the server when an alert is triggered

### What and How?

It'd allow for running commands as console when an alert is triggered.
Could be implemented pretty simply with the current alerts.yml like so 
```yml
- Trigger: PlayerKickEvent
  Channel: general
  Conditions:
    - '#event.getPlayer().isBanned()'
  Embed:
    Color: "#ff0000"
    ThumbnailUrl: "https://cdn.discordapp.com/attachments/895784266976329739/979605823925919784/unknown.png"
    Author:
      ImageUrl: "{embedavatarurl}"
      Name: "🔨 Banned %cmi_user_nameplate_prefix%${#event.getPlayer().getDisplayName()}"
    Description: "**Reason:** ${#server.getBanList(T(org.bukkit.BanList.Type).NAME).getBanEntry(#event.getPlayer().name).getReason()}"
  Commands:
    - 'co rollback radius:#global time:1000d user:{#event.getPlayer().name}'

```

### Are there alternatives?

ConditionalEvents can do this but it'd be nice to have it bundled with alerts

### Checks

- [x] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.
