### ISSUE TITLE
PlayerDeathEvent alert doesn't work properly.

### ISSUE THREAD

**Issue by DanishAnodher** [DiscordSRV/DiscordSRV#1684]
### Expected behavior

```
- Trigger: PlayerDeathEvent
    Channel: deaths
    Embed:
      Color: "#c0392b" # Reddish color for death alerts
      Author:
        ImageUrl: "{embedavatarurl}"
        Name: "${deathMessage}"
      Fields:
        - "Level;${player.getLevel()};true"
        - "Coords;```${player.getLocation().getBlockX() + ' ' + player.getLocation().getBlockY() + ' ' + player.getLocation().getBlockZ()}```;true"
      Description: "**Items**\n```${drops.![type + ' x' + amount]}```"
```

I got this to work 2 times. But it isn't working eversince. 

![image](https://github.com/DiscordSRV/DiscordSRV/assets/55613161/cff33d02-815a-4862-8725-119238ae2d15)

### Actual behavior

Now It won't send anything to discord.

All the other Events and Command Triggers seem to be working fine.

### Steps to reproduce

The code have been mentioned above. 

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

### Anything else

I have 1.27.0 Snapshot which is the latest in Aternos > Plugins
