### ISSUE TITLE
 SRV Voice Function Problem

### ISSUE THREAD

**Issue by minexo79** [DiscordSRV/DiscordSRV#676]
I just open the voice function and then he show the attention message.
The attention message keeps popping up when there's >2 people meet up and sprinting too fast.
this is my spec and attation message:
```yaml
GCP: c2-standard-4 (4-core/16G ram)
SSD: 120G
OS: Ubuntu 18.04 LTS
```

![attation mesage](https://i.imgur.com/rijXzPB.png)
