### ISSUE TITLE
Formatting MinecraftPlayer(first)JoinMessage

### ISSUE THREAD

**Issue by x1p** [DiscordSRV/DiscordSRV#757]
I'm trying to use formatting in the messages. However this doesn't seem to work anymore.
It worked fine in 1.18.4
Broke since 1.19.0 (and dev build)

Example:
```YAML
MinecraftPlayerJoinMessage: 
  Enabled: false
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#00ff00"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: ":tada: **%username% joined the server**"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false
```
Using formatting in the `DiscordChatChannelServer(Startup/Shutdown)Message` however works fine.

**Comment by Vankka** [comment]
You have `Enabled: false`

**Comment by x1p** [comment]
Yes because I disabled this one. I used this one as a test for the `MinecraftPlayerFirstJoinMessage` message. Because I don't have that many new players to test with

**Comment by x1p** [comment]
Another example which doesn't work
```yaml
MinecraftPlayerLeaveMessage: 
  Enabled: true
  Webhook:
    Enable: false
    AvatarUrl: "%botavatarurl%"
    Name: "%botname%"
  Content: ""
  Embed:
    Enabled: true
    Color: "#ff0000"
    Author:
      ImageUrl: "%embedavatarurl%"
      Name: ":tada: **%displayname% left**"
      Url: ""
    ThumbnailUrl: ""
    Title:
      Text: ""
      Url: ""
    Description: ""
    Fields: []
    ImageUrl: ""
    Footer:
      Text: ""
      IconUrl: ""
    Timestamp: false
```
